### ISSUE TITLE
Updated User and Meeting model

### ISSUE THREAD

**Issue by saboonikhil** [jaykhatri0875/meeting-room-booking-system#7]
Heads Up:
1. Ensured attribute name for id remains uniform for all databases - `uID`
2. In order to generate custom ids (mixture of characters and numbers) for `uID`: String has been chosen (Currently random uuid is being generated)
3. Enumerations are used instead of String for attributes with pre-defined values

Need to check:
For references to other database, whether to use string or the object itself. I am not sure how it works for SQL. Like for attendees: I have used User[ ] (Array of user objects) instead of String[ ] (Array of user ids)

Please drop your comments here as soon as you review both the models in my branch - User and Meeting. @jaykhatri0875 @Shivani0608 @HrushabhHirudkar @grvanand

**Comment by HrushabhHirudkar** [comment]
In Meeting : 
      For the User[] - we can store the uid in an array and get the users by fetching from database using fetchByID - It will reduce space , but increase the time to compute, So anything could work.

Rest is fine according to me.

**Comment by saboonikhil** [comment]
> In Meeting :
> For the User[] - we can store the uid in an array and get the users by fetching from database using fetchByID - It will reduce space , but increase the time to compute, So anything could work.
> 
> Rest is fine according to me.

Yes either way it works. We need to decide on the basis of its usage.

**Comment by HrushabhHirudkar** [comment]
> > In Meeting :
> > For the User[] - we can store the uid in an array and get the users by fetching from database using fetchByID - It will reduce space , but increase the time to compute, So anything could work.
> > Rest is fine according to me.
> 
> Yes either way it works. We need to decide on the basis of its usage.

If while taking input if we take the uid of members then we could store it directly but if we take input as name of members then  we will need to extract the uid , so there we could directly store the user as we are extracting details from the table

**Comment by saboonikhil** [comment]
> > > In Meeting :
> > > For the User[] - we can store the uid in an array and get the users by fetching from database using fetchByID - It will reduce space , but increase the time to compute, So anything could work.
> > > Rest is fine according to me.
> > 
> > 
> > Yes either way it works. We need to decide on the basis of its usage.
> 
> If while taking input if we take the uid of members then we could store it directly but if we take input as name of members then we will need to extract the uid , so there we could directly store the user as we are extracting details from the table

For adding attendees, we need to fetch all user objects from the database and it is on us what to send to the frontend. 
As in this case, we need checkboxes against user name/email - we already have everything for input. 

We need to see more cases like these.

**Comment by Shivani0608** [comment]
I think for time being let us go with user objects, because we will have to fetch those users from the database at some point of time. So better we already store them as objects.

**Comment by saboonikhil** [comment]
Btw I forgot to add - I am using long for storing `startTime`/`endTime` in milliseconds

This will save a lot of computation I feel. Let me know your thoughts..

**Comment by Shivani0608** [comment]
Why don't you use time datatype of sql, it will be easy to even recognize whether it is AM or PM. And may be you will also have to add an attribute to store the date of meeting.

**Comment by saboonikhil** [comment]
> Why don't you use time datatype of sql, it will be easy to even recognize whether it is AM or PM. And may be you will also have to add an attribute to store the date of meeting.

Time in milliseconds has in-built date and also considers AM/PM. Check this out: https://currentmillis.com/tutorials/system-currentTimeMillis.html

1. Date attribute is vague. What if the meeting starts today and ends tomorrow? We can't have separate date attributes for start and end
2. You don't need to remember the date format in which database is storing the time.
3. Milliseconds can easily be parsed to any date format as per convenience
4. We don't have the usage of timezone here but still it takes care of that as well.

**Comment by Shivani0608** [comment]
> > Why don't you use time datatype of sql, it will be easy to even recognize whether it is AM or PM. And may be you will also have to add an attribute to store the date of meeting.
> 
> Time in milliseconds has in-built date and also considers AM/PM. Check this out: https://currentmillis.com/tutorials/system-currentTimeMillis.html
> 
>     1. Date attribute is vague. What if the meeting starts today and ends tomorrow? We can't have separate date attributes for start and end
> 
>     2. You don't need to remember the date format in which database is storing the time.
> 
>     3. Milliseconds can easily be parsed to any date format as per convenience
> 
>     4. We don't have the usage of timezone here but still it takes care of that as well.

Okay then go for it
